# This file was generated by GoReleaser. DO NOT EDIT.
cask "cold2warm" do
  name "cold2warm"
  desc "A CLI tool to bulk-restore S3 objects from archival storage classes using concurrent goroutines."
  homepage "https://github.com/veerendra2/cold2warm"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cold2warm"

  on_macos do
    on_intel do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_darwin_x86_64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "90357223c0074c6ff49bfcb1b915e6fcba286a8f82607f50799e986fd1e06f52"
    end
    on_arm do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_darwin_arm64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "6804dfdabd98d6c86ba99d8790a3dfb46469d66ce5077d5755ba3dbae81fea3e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_linux_x86_64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "31ddea4cce824db822bd0a20fbfeb473df6f67f8873033db9002d97185536e97"
    end
    on_arm do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_linux_arm64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "e62a4e3c153191a3c69ea3e11a5b6098fccf078631f060f2fb1246216c048235"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cold2warm"]
    end
  end

  # No zap stanza required
end
