# This file was generated by GoReleaser. DO NOT EDIT.
cask "cold2warm" do
  name "cold2warm"
  desc "A CLI tool to bulk-restore S3 objects from archival storage classes using concurrent goroutines."
  homepage "https://github.com/veerendra2/cold2warm"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cold2warm"

  on_macos do
    on_intel do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_darwin_x86_64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "aea3644455d9a3f9eaa25194256e681c18b6447f3991d74e9e17869c45d34bda"
    end
    on_arm do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_darwin_arm64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "14944567f084a271393093bbc135898ac8f6c87e013b974dfdfaa72cc3312da3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_linux_x86_64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "75f35cf88571193423d2487fe60850a4439155ff7f358f2bb64d2cd0e3c30752"
    end
    on_arm do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_linux_arm64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "85a3ff47196d36745db2af66724f2bd8ea66787aaa51c470b82fbe5bb8c80ca1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cold2warm"]
    end
  end

  # No zap stanza required
end
