# This file was generated by GoReleaser. DO NOT EDIT.
cask "cold2warm" do
  name "cold2warm"
  desc "A CLI tool to bulk-restore S3 objects from archival storage classes using concurrent goroutines."
  homepage "https://github.com/veerendra2/cold2warm"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cold2warm"

  on_macos do
    on_intel do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_darwin_x86_64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "d54a7660c2d227fa567ed9e2e96b6391f50ee76b6f333c6204e85019217a0dbb"
    end
    on_arm do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_darwin_arm64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "9a78318bcd29f092b38e10ad2583056aebf160704a234cf8eb6f2c4426afec74"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_linux_x86_64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "e941af89a4d68ea00085d226a7f58aaee5ce7dc0ef20ae62c838822bc6e22c47"
    end
    on_arm do
      url "https://github.com/veerendra2/cold2warm/releases/download/v#{version}/cold2warm_linux_arm64.zip",
        verified: "github.com/veerendra2/cold2warm"
      sha256 "7b807febfbaa579f086e443a02cf14b347193cd24a22a8a233b51779e0f30ccd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cold2warm"]
    end
  end

  # No zap stanza required
end
