# This file was generated by GoReleaser. DO NOT EDIT.
cask "quotations" do
  name "quotations"
  desc "A tool to display random inspirational quotes and famous dialogues from movies and TV shows on your CLI. 😎"
  homepage "https://github.com/veerendra2/quotations"
  version "1.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quotations"

  on_macos do
    on_intel do
      url "https://github.com/veerendra2/quotations/releases/download/v#{version}/quotations_darwin_x86_64.zip",
        verified: "github.com/veerendra2/quotations"
      sha256 "e8bc0c1400f9d40c465e176366571c26b2fec0a4e7da2d267f644db1e976f8f0"
    end
    on_arm do
      url "https://github.com/veerendra2/quotations/releases/download/v#{version}/quotations_darwin_arm64.zip",
        verified: "github.com/veerendra2/quotations"
      sha256 "05737dd0c391e2db9f8e84be71cc243bb7d6cd8d45d86c5e00bcbb5f0dce12de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/veerendra2/quotations/releases/download/v#{version}/quotations_linux_x86_64.zip",
        verified: "github.com/veerendra2/quotations"
      sha256 "b951ae51b9d9e2e00dbdc22732a82a810a20039da2677ba6c803e2ddc4d82b86"
    end
    on_arm do
      url "https://github.com/veerendra2/quotations/releases/download/v#{version}/quotations_linux_arm64.zip",
        verified: "github.com/veerendra2/quotations"
      sha256 "64c0b26a75b4746d6350caf0fe4b34cf3e87a57669f49a9f5d9172eb1a4b7fd6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/quotations"]
    end
  end

  caveats do
    "ℹ️ To display a random quote when terminal opens, add it to your shell"
    "💡 Example for Bash:"
    "echo quotations >> ~/.bashrc"
  end

  # No zap stanza required
end
