# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiseDotfilesUninstall < Formula
  desc "The missing uninstaller companion for mise's dotfiles (Until native support)."
  homepage "https://github.com/veerendra2/mise-dotfiles-uninstall"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.1.0/mise-dotfiles-uninstall_darwin_x86_64.zip"
      sha256 "90d8117df3f43953ebb3da584ca76aba6c978537b964284af75ae6bf9dc241da"

      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.1.0/mise-dotfiles-uninstall_darwin_arm64.zip"
      sha256 "077c1f0277e401842811328703feaf57ca54b474fa4873f9a6ec7e6f1c572ae0"

      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.1.0/mise-dotfiles-uninstall_linux_x86_64.zip"
      sha256 "14948dab4f62996e0d290b36708ebf98f8938d986c6a39f31a808ede9b48fb98"
      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.1.0/mise-dotfiles-uninstall_linux_arm64.zip"
      sha256 "34962300c7ef83de25d9279fb06594f5a9e0dec0430f3f297f63b3beead845b0"
      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
  end
end
