# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiseDotfilesUninstall < Formula
  desc "The missing uninstaller companion for mise's dotfiles (Until native support)."
  homepage "https://github.com/veerendra2/mise-dotfiles-uninstall"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.0.0/mise-dotfiles-uninstall_darwin_x86_64.zip"
      sha256 "1c3937239b0862fb11c736fcfe491fd7fc4cc0e061134eb39617e82015c01703"

      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.0.0/mise-dotfiles-uninstall_darwin_arm64.zip"
      sha256 "b4e60c0659b293d6ed06cfbe1b123fd43b3935ecc071be283761424b056bc31b"

      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.0.0/mise-dotfiles-uninstall_linux_x86_64.zip"
      sha256 "90bc804f782bd6a696bc8d51ee77d066e37c87e78313f794612e49df20d60bef"
      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/mise-dotfiles-uninstall/releases/download/v1.0.0/mise-dotfiles-uninstall_linux_arm64.zip"
      sha256 "caf4f472f373def2050c1c6f164d5774a1b646392df101402739f8a57aa91b8b"
      define_method(:install) do
        bin.install "mise-dotfiles-uninstall"
      end
    end
  end
end
