# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quotations < Formula
  desc "A tool to display random inspirational quotes and famous dialogues from movies and TV shows on your CLI. 😎"
  homepage "https://github.com/veerendra2/quotations"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.5/quotations_Darwin_x86_64.zip"
      sha256 "ba34931bf010531cd8be10039bca076402ffeba33f30001bf5a5fe54baca54ff"

      def install
        bin.install "quotations"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.5/quotations_Darwin_arm64.zip"
      sha256 "2339b2f3b6fe62183eb9ccda3108afe9ccb0de17d8cd7f95f6de82b6ddad5ec3"

      def install
        bin.install "quotations"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.5/quotations_Linux_x86_64.zip"
      sha256 "253e550529e4270f8c5e7118857c65d4de7083b57a452f69121e5bb91af9bff4"
      def install
        bin.install "quotations"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.5/quotations_Linux_arm64.zip"
      sha256 "db6c98689b98bef5cc73c4f7d1e8311fcdb81e77ca3a3af15e92a61c5763af40"
      def install
        bin.install "quotations"
      end
    end
  end

  def caveats
    <<~EOS
      ℹ️ To display a random quote when terminal opens, add it to your shell
      💡 Example for Bash:
      echo "quotations" >> ~/.bashrc
    EOS
  end
end
