# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quotations < Formula
  desc "A tool to display random inspirational quotes and famous dialogues from movies and TV shows on your CLI. 😎"
  homepage "https://github.com/veerendra2/quotations"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.4/quotations_Darwin_x86_64.zip"
      sha256 "53752b7d94577ce822c629a84c97efd85991016533d57997e234d56709d54747"

      def install
        bin.install "quotations"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.4/quotations_Darwin_arm64.zip"
      sha256 "448d33157dc11aadc6f3e6f295cbc1ec63cef85d4141716e3a9e7b1e3ac34ef8"

      def install
        bin.install "quotations"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.4/quotations_Linux_x86_64.zip"
      sha256 "226512804beae96fb5e49ea30ca40911bbc726a58d9d6883d4024e2f695d6415"
      def install
        bin.install "quotations"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.4/quotations_Linux_arm64.zip"
      sha256 "4992f48099581d1be6f90317d2bb7954ba97ebc7f2e9063cef3d5cc83ad928d6"
      def install
        bin.install "quotations"
      end
    end
  end

  def caveats
    <<~EOS
      ℹ️ To display a random quote when terminal opens, add it to your shell
      💡 Example for Bash:
      echo "quotations" >> ~/.bashrc
    EOS
  end
end
