# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quotations < Formula
  desc "A tool to display random inspirational quotes and famous dialogues from movies and TV shows on your CLI. 😎"
  homepage "https://github.com/veerendra2/quotations"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.2/quotations_Darwin_x86_64.zip"
      sha256 "582ca44daef4b56d231b43bcc3cdd367a198061d686dd4b32428a83ff385eea5"

      def install
        bin.install "quotations"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/veerendra2/quotations/releases/download/v1.0.2/quotations_Darwin_arm64.zip"
      sha256 "8bb9f808bf28479f9385a20d187185f5b360b453c42b4f96f509c35e581c1e96"

      def install
        bin.install "quotations"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/veerendra2/quotations/releases/download/v1.0.2/quotations_Linux_x86_64.zip"
        sha256 "64a8975671a17907c67ef73baff6d21f90260640222703e910d0b08edfed2a86"

        def install
          bin.install "quotations"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/veerendra2/quotations/releases/download/v1.0.2/quotations_Linux_arm64.zip"
        sha256 "8e463fc3b7c59c537f8c932ba22f583bb24dc7845ac275ce3ecc1b00b23e027d"

        def install
          bin.install "quotations"
        end
      end
    end
  end

  def caveats
    <<~EOS
      ℹ️ To display a random quote when terminal opens, add it to your shell
      💡 Example for Bash:
      echo "quotations" >> ~/.bashrc
    EOS
  end
end
