# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symlinkr < Formula
  desc "Declarative symlink manager."
  homepage "https://github.com/veerendra2/symlinkr"
  version "1.0.1"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/veerendra2/symlinkr/releases/download/v1.0.1/symlinkr_darwin_x86_64.zip"
      sha256 "44cab044f7e7df7d0e3a3ec540cbb23a9ca35164686ec0eab1430f7d4b8d8c46"

      define_method(:install) do
        bin.install "symlinkr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/veerendra2/symlinkr/releases/download/v1.0.1/symlinkr_darwin_arm64.zip"
      sha256 "02a949ecb2de7659f4cffdf6855a9515061b52b71e083d23770771aa839dc602"

      define_method(:install) do
        bin.install "symlinkr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/symlinkr/releases/download/v1.0.1/symlinkr_linux_x86_64.zip"
      sha256 "bed26ae235a7c2e7474b4e51a56f1de953b053b3a7b201b19c0da6a2b8bc3b69"
      define_method(:install) do
        bin.install "symlinkr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/veerendra2/symlinkr/releases/download/v1.0.1/symlinkr_linux_arm64.zip"
      sha256 "26a231f75fe02623000b89d05f28f1b17048a4c00e37aea2d41ae8e8f5d45f47"
      define_method(:install) do
        bin.install "symlinkr"
      end
    end
  end
end
